SET(SECP256K1_SEARCH_PREFIXES
  /usr
  /usr/local
  /opt/homebrew
  /opt/local
  /var
)

FIND_PATH(SECP256K1_INCLUDE_DIRS
  NAMES secp256k1.h secp256k1_recovery.h
  PATH_SUFFIXES include/secp256k1 include
  PATHS ${SECP256K1_SEARCH_PREFIXES}
  NO_CACHE
)

FIND_LIBRARY(SECP256K1_LINK_LIBRARIES
  NAMES secp256k1
  PATH_SUFFIXES lib64 lib
  PATHS ${SECP256K1_SEARCH_PREFIXES}
  NO_CACHE
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(secp256k1 REQUIRED_VARS
  SECP256K1_INCLUDE_DIRS
  SECP256K1_LINK_LIBRARIES)
