SET(TOMMATH_SEARCH_PREFIXES
  /usr
  /usr/local
  /opt/homebrew
  /opt/local
  /var
)

FIND_PATH(TOMMATH_INCLUDE_DIRS
  NAMES tommath.h
  PATH_SUFFIXES include/tommath include
  PATHS ${TOMMATH_SEARCH_PREFIXES}
  NO_CACHE
)

FIND_LIBRARY(TOMMATH_LINK_LIBRARIES
  NAMES tommath
  PATH_SUFFIXES lib64 lib
  PATHS ${TOMMATH_SEARCH_PREFIXES}
  NO_CACHE
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(tommath REQUIRED_VARS
  TOMMATH_INCLUDE_DIRS TOMMATH_LINK_LIBRARIES)
