SET(GMP_SEARCH_PREFIXES
  /usr
  /usr/local
  /opt/homebrew
  /opt/local
  /var
)

FIND_PATH(GMP_INCLUDE_DIRS
  NAMES gmp.h
  PATH_SUFFIXES include/gmp include
  PATHS ${GMP_SEARCH_PREFIXES}
  NO_CACHE
)

FIND_LIBRARY(GMP_LINK_LIBRARIES
  NAMES gmp
  PATH_SUFFIXES lib64 lib
  PATHS ${GMP_SEARCH_PREFIXES}
  NO_CACHE
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(gmp REQUIRED_VARS
  GMP_INCLUDE_DIRS GMP_LINK_LIBRARIES)
