SET(SECP256K1_SEARCH_PREFIXES
  /usr
  /usr/local
  /opt/homebrew
  /opt/local
  /var
)

FIND_PATH(SECP256K1_INCLUDE_DIRS
  NAMES secp256k1.h secp256k1_recovery.h
  PATH_SUFFIXES include/secp256k1 include
  PATHS ${SECP256K1_SEARCH_PREFIXES}
  NO_CACHE
)

FIND_LIBRARY(SECP256K1_LINK_LIBRARIES
  NAMES secp256k1
  PATH_SUFFIXES lib64 lib
  PATHS ${SECP256K1_SEARCH_PREFIXES}
  NO_CACHE
)

IF(SECP256K1_INCLUDE_DIRS STREQUAL "SECP256K1_INCLUDE_DIRS-NOTFOUND")
  MESSAGE(FATAL_ERROR "ethc: could not find secp256k1 include directory.")
ENDIF()

IF(SECP256K1_LINK_LIBRARIES STREQUAL "SECP256K1_LINK_LIBRARIES-NOTFOUND")
  MESSAGE(FATAL_ERROR "ethc: could not find secp256k1 library path.")
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(secp256k1 REQUIRED_VARS
  SECP256K1_INCLUDE_DIRS
  SECP256K1_LINK_LIBRARIES)
