name: ci-unix

on:
  push:
    branches:
     - '*'
    paths:
    - '.github/**'
    - 'src/**'
    - 'include/**'
    - 'test/**'
    - 'libkeccak/**'
    - 'CMakeLists.txt'
  pull_request:
    branches:
     - '*'
    paths:
    - '.github/**'
    - 'src/**'
    - 'include/**'
    - 'test/**'
    - 'libkeccak/**'
    - 'CMakeLists.txt'
     
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DETHC_BUILD_TESTS=ON -DETHC_TOMMATH_STATIC=ON -DETHC_SECP256K1_STATIC=ON ..
          make
          ls -lh
      - name: Test
        run: |
          cd build
          make test ARGS="-V"
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DETHC_BUILD_TESTS=ON -DETHC_TOMMATH_STATIC=ON -DETHC_SECP256K1_STATIC=ON ..
          make
          ls -lh
      - name: Test
        run: |
          cd build
          make test ARGS="-V"
